#!/bin/bash

open() {
    local workspace="$1"
    shift
    aerospace workspace "$workspace"
    sleep 2
    for app in "$@"; do
        open c-a "$app"
    done
    sleep 2
}

open 1 "Ghostty"
open 2 "VSCode"
open 3 "Vivaldi"
open 4 "Music"
open 5 "Vesktop"
